#!/bin/sh
scp -r ms@10.3.11.50:/srv/www/css .
scp -r ms@10.3.11.50:/srv/www/css3menu .
scp -r ms@10.3.11.50:/srv/www/design .
scp -r ms@10.3.11.50:/srv/www/js .
scp -r ms@10.3.11.50:/srv/www/sql .
scp -r ms@10.3.11.50:/srv/www/tpl .
scp ms@10.3.11.50:/srv/www/*.* .
scp ms@10.3.11.50:/srv/www/.gitignore .
