/* Formatted on 23/09/2014 22:22:33 (QP5 v5.227.12220.39724) */
  SELECT zf.id,
         zf.ff_id,
         zf.val_string,
         zf.val_textarea,
         zf.val_number_int,
         zf.val_number,
         zf.val_list,
         zf.val_formula,
         TO_CHAR (zf.val_datepicker, 'dd.mm.yyyy') val_datepicker,
         zf.val_file,
         zf.val_bool,
         zf.rep_val_string,
         zf.rep_val_textarea,
         zf.rep_val_number_int,
         zf.rep_val_number,
         zf.rep_val_list,
         zf.rep_val_formula,
         TO_CHAR (zf.rep_val_datepicker, 'dd.mm.yyyy') rep_val_datepicker,
         zf.rep_val_file,
         zf.rep_val_bool,
         f.name,
         f.TYPE,
         f.class,
         f.rep_name,
         f.rep_required,
         f.rep_r_visible,
         f.formula,
         f.rep_formula,
         f.var_name,
         f.rep_var_name
    FROM bud_ru_zay_ff zf, bud_ru_ff f
   WHERE zf.z_id = :z_id AND zf.ff_id = f.id
ORDER BY f.sort