/* Formatted on 1/11/2016 12:40:18  (QP5 v5.252.13127.32867) */
INSERT INTO nets_plan_month (id_net,
                             YEAR,
                             MONTH,
                             statya,
                             descript,
                             payment_type,
                             payment_format,
                             bonus,
                             price,
                             cnt,
                             plan_type,
                             mkk_ter,
                             tn_confirmed,
                             payer,
                             row_id)
   SELECT n1.id_net,
          n1.YEAR,
          n1.MONTH,
          n1.statya,
          n1.descript,
          n1.payment_type,
          n1.payment_format,
          n1.bonus,
          n1.price,
          n1.cnt,
          :plan_type,
          mkk_ter,
          :tn_confirmed,
          n1.payer,
          n1.row_id
     FROM nets_plan_month n1
    WHERE n1.ID = :ID