/* Formatted on 28.12.2012 9:53:27 (QP5 v5.163.1008.3004) */
SELECT TO_CHAR (CASE WHEN TO_CHAR (SYSDATE, 'dd') < 25 THEN ADD_MONTHS (TRUNC (SYSDATE, 'mm'), -1) ELSE TRUNC (SYSDATE, 'mm') END, 'month yyyy') t,
       TO_CHAR (CASE WHEN TO_CHAR (SYSDATE, 'dd') < 25 THEN ADD_MONTHS (TRUNC (SYSDATE, 'mm'), -1) ELSE TRUNC (SYSDATE, 'mm') END, 'dd.mm.yyyy') d
  FROM DUAL